In [158]:
import pandas as pd
from datetime import datetime

In [242]:
df_user= pd.read_csv('nuevouser.csv')
df_user

                   user_id  item_id  playtime_forever
0        76561197970982479       10                 6
1        76561197970982479       20                 0
2        76561197970982479       30                 7
3        76561197970982479       40                 0
4        76561197970982479       50                 0
...                    ...      ...               ...
5094100  76561198329548331   346330                 0
5094101  76561198329548331   373330                 0
5094102  76561198329548331   388490                 3
5094103  76561198329548331   521570                 4
5094104  76561198329548331   519140                 3

[5094105 rows x 3 columns]

In [189]:
df_review=pd.read_csv('review.csv')
df_review

                 user_id  item_id  recommend  sentiment_analysis  year
0      76561197970982479     1250       True                   2  2011
1      76561197970982479    22200       True                   2  2011
2      76561197970982479    43110       True                   2  2011
3                js41637   251610       True                   2  2014
4                js41637   227300       True                   0  2013
...                  ...      ...        ...                 ...   ...
59300  76561198312638244       70       True                   2  2023
59301  76561198312638244   362890       True                   2  2023
59302        LydiaMorley   273110       True                   2  2023
59303        LydiaMorley      730       True                   2  2023
59304        LydiaMorley      440       True                   2  2023

[59305 rows x 5 columns]

In [5]:
df_items=pd.read_csv('juego.csv')
df_items

,publisher,title,price,item_id,developer,release_year,Accounting,Action,Adventure,Animation &amp; Modeling,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,Kotoshiro,Lost Summoner Kitty,4.99,761140,Kotoshiro,2018,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
1,"Making Fun, Inc.",Ironbound,0.00,643980,Secret Level SRL,2018,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
2,Poolians.com,Real Pool 3D - Poolians,0.00,670290,Poolians.com,2017,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
3,彼岸领域,弹炸人2222,0.99,767400,彼岸领域,2017,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
4,NaN,NaN,2.99,773570,NaN,0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32128,Ghost_RUS Games,Russian Roads,1.99,773640,"Nikita ""Ghost_RUS""",2018,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
32129,Sacada,EXIT 2 - Directions,4.99,733530,Sacada,2018,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
32130,Laush Studio,NaN,1.99,610660,Laush Dmitriy Sergeevich,2018,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
32131,SIXNAILS,NaN,4.99,658870,"xropi,stev3ns",2017,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32132,NaN,NaN,4.99,681550,NaN,0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [44]:
def userdata(user_id: str):
    """
    Esta función cuenta cuántas veces se repite un usuario en la columna 'user_id' del DataFrame df.

    Args:
    user_id (str): El usuario que deseas contar en formato de cadena.

    Returns:
    El número de repeticiones del usuario en la columna 'user_id'.
    """
    # Asumiendo que df_users es el DataFrame que contiene los datos
    
    contador = df_datauser['user_id'].value_counts().get(user_id, 0)
    

    print(f"El usuario {user_id} se repite {contador} veces en la columna 'user_id'.")
    return contador

# Ejemplo de uso:
# Supongamos que user_id es el usuario que quieres contar
user_id = '76561197970982479'
repeticiones = userdata(user_id)

El usuario 76561197970982479 se repite 277 veces en la columna 'user_id'.

In [128]:
# Realiza la relación entre df_user y df_item en base a 'item_id' y agrega la columna 'price' de df_item
df_datauser = pd.merge(df_user[['user_id', 'item_id']], df_items[['item_id', 'price']], on='item_id', how='left')
df_datauser = pd.merge(df_datauser, df_review[['user_id', 'item_id', 'recommend']], on=['user_id', 'item_id'], how='left')

# la columna 'user_id' se pasara a minusculas
df_datauser['user_id'] = df_datauser['user_id'].str.lower()
df_datauser

                   user_id  item_id  price recommend
0        76561197970982479       10   9.99       NaN
1        76561197970982479       20   4.99       NaN
2        76561197970982479       30   4.99       NaN
3        76561197970982479       40   4.99       NaN
4        76561197970982479       50   4.99       NaN
...                    ...      ...    ...       ...
5094805  76561198329548331   346330   0.00       NaN
5094806  76561198329548331   373330   0.00       NaN
5094807  76561198329548331   388490   0.00       NaN
5094808  76561198329548331   521570   0.00       NaN
5094809  76561198329548331   519140    NaN       NaN

[5094810 rows x 4 columns]

In [67]:
#se revisa los valores nulos en la columna
df_datauser['recommend'].values()

TypeError: 'numpy.ndarray' object is not callable

In [41]:
# Reemplaza los valores nulos en la columna 'recommend' por False
df_datauser['recommend'].fillna(False, inplace=True)

In [247]:
def userdata(user_id: str):
    user_id = user_id.lower()
    comprobar = list(set(df_datauser['user_id']))
    if user_id in comprobar:
           
        """
        Esta función cuenta cuántas veces se repite un usuario en la columna 'user_id' del DataFrame df.
        Luego suma la columna 'price' de las filas correspondientes al usuario.

        Args:
        user_id (str): El usuario que deseas contar en formato de cadena.

        Returns:
        El número de repeticiones del usuario en la columna 'user_id', la suma de la columna 'price' y
        el promedio de recomendaciones para este usuario
        """
        # Filtrar el DataFrame por el usuario especificado
        user_data = df_datauser[df_datauser['user_id'] == user_id]
        
        # Contar las repeticiones del usuario
        contador = user_data.shape[0]
        
        # Sumar la columna 'price' para las filas correspondientes al usuario
        suma_precios = user_data['price'].sum()
        # Filtrar las filas donde la columna 'recommend' es True y luego sumar esos valores para dividirlos entre el contador
        promedio = (user_data[user_data['recommend'] == True]['recommend'].sum())*100/contador


        print(f"El usuario {user_id} tiene {contador} items.")
        print(f"La suma dinero gastado para este usuario es: {suma_precios}")
        print(f"El porcentaje de recomendaciones para este usuario es: {promedio:.2f} %")
    
        return 
    else:
        print('Ingrese nuevamente el usuario')
        return

In [248]:
userdata('76561197970982479')

El usuario 76561197970982479 tiene 277 items.
La suma dinero gastado para este usuario es: 3424.31
El porcentaje de recomendaciones para este usuario es: 1.08 %

In [191]:
# Convertir la columna 'year' en una variable de tiempo
df_review['year'] = pd.to_datetime(df_review['year'], format='%Y')

In [243]:

def countreviews(start_date, end_date: str):
    # Convertir las fechas de inicio y fin en objetos datetime
    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)

    # Filtrar el DataFrame para obtener las revisiones en el rango de fechas
    filtered_df = df_review[(df_review['year'] >= start_date)& (df_review['year'] <= end_date)]

        
    # Contar los comentarios hechos por los usuarios
    cont = filtered_df.shape[0]  
    
    porcentaje = (filtered_df[filtered_df['recommend'] == True]['recommend'].sum())*100/cont

    print(f'Cantidad de usuarios que realizaron reviews entre las fechas {start_date} y {end_date} es de: {cont}')
    print(f"El porcentaje de juegos que fueron recomendados es: {porcentaje:.2f} %")
    
    return

In [244]:
countreviews('2011-01-01', '2012-12-31')

Cantidad de usuarios que realizaron reviews entre las fechas 2011-01-01 00:00:00 y 2012-12-31 00:00:00 es de: 1747
El porcentaje de juegos que fueron recomendados es: 98.63 %

In [249]:
# Realiza la relación entre df_user y df_item en base a 'item_id' y agrega la columna 'price' de df_item
df_genre = pd.merge(df_user, df_items, on='item_id', how='right')
df_genre

,user_id,item_id,playtime_forever,publisher,title,price,developer,release_year,Accounting,Action,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,NaN,761140,NaN,Kotoshiro,Lost Summoner Kitty,4.99,Kotoshiro,2018,False,True,...,False,False,False,True,False,False,True,False,False,False
1,NaN,643980,NaN,"Making Fun, Inc.",Ironbound,0.00,Secret Level SRL,2018,False,False,...,False,True,False,False,False,False,True,False,False,False
2,NaN,670290,NaN,Poolians.com,Real Pool 3D - Poolians,0.00,Poolians.com,2017,False,False,...,False,False,False,True,False,True,False,False,False,False
3,NaN,767400,NaN,彼岸领域,弹炸人2222,0.99,彼岸领域,2017,False,True,...,False,False,False,False,False,False,False,False,False,False
4,NaN,773570,NaN,NaN,NaN,2.99,NaN,0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4267767,NaN,773640,NaN,Ghost_RUS Games,Russian Roads,1.99,"Nikita ""Ghost_RUS""",2018,False,False,...,False,False,False,True,False,False,True,False,False,False
4267768,NaN,733530,NaN,Sacada,EXIT 2 - Directions,4.99,Sacada,2018,False,False,...,False,False,False,False,False,False,True,False,False,False
4267769,NaN,610660,NaN,Laush Studio,NaN,1.99,Laush Dmitriy Sergeevich,2018,False,False,...,False,False,True,True,False,False,False,False,False,False
4267770,NaN,658870,NaN,SIXNAILS,NaN,4.99,"xropi,stev3ns",2017,False,False,...,False,False,False,False,False,False,False,False,False,False
4267771,NaN,681550,NaN,NaN,NaN,4.99,NaN,0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [250]:
df_genre=df_genre.dropna(subset=['user_id'])
df_genre

,user_id,item_id,playtime_forever,publisher,title,price,developer,release_year,Accounting,Action,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
27,UTNerd24,282010,5.0,Stainless Games Ltd,Carmageddon Max Pack,9.99,Stainless Games Ltd,1997,False,True,...,False,False,True,False,False,False,False,False,False,False
28,I_DID_911_JUST_SAYING,282010,0.0,Stainless Games Ltd,Carmageddon Max Pack,9.99,Stainless Games Ltd,1997,False,True,...,False,False,True,False,False,False,False,False,False,False
29,76561197962104795,282010,0.0,Stainless Games Ltd,Carmageddon Max Pack,9.99,Stainless Games Ltd,1997,False,True,...,False,False,True,False,False,False,False,False,False,False
30,r3ap3r78,282010,0.0,Stainless Games Ltd,Carmageddon Max Pack,9.99,Stainless Games Ltd,1997,False,True,...,False,False,True,False,False,False,False,False,False,False
31,saint556,282010,13.0,Stainless Games Ltd,Carmageddon Max Pack,9.99,Stainless Games Ltd,1997,False,True,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4267750,76561198273508956,80,0.0,Valve,Robotpencil Presents: Creative Composition,9.99,Valve,2004,False,True,...,False,False,False,False,False,False,False,False,False,False
4267751,76561198282090798,80,0.0,Valve,Robotpencil Presents: Creative Composition,9.99,Valve,2004,False,True,...,False,False,False,False,False,False,False,False,False,False
4267752,943525,80,0.0,Valve,Robotpencil Presents: Creative Composition,9.99,Valve,2004,False,True,...,False,False,False,False,False,False,False,False,False,False
4267753,76561198283312749,80,9.0,Valve,Robotpencil Presents: Creative Composition,9.99,Valve,2004,False,True,...,False,False,False,False,False,False,False,False,False,False
4267754,76561198312638244,80,99.0,Valve,Robotpencil Presents: Creative Composition,9.99,Valve,2004,False,True,...,False,False,False,False,False,False,False,False,False,False

In [251]:
df_genre = df_genre.drop(columns=['publisher', 'title', 'price', 'developer', 'release_year'])
df_genre

,user_id,item_id,playtime_forever,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
27,UTNerd24,282010,5.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
28,I_DID_911_JUST_SAYING,282010,0.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
29,76561197962104795,282010,0.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
30,r3ap3r78,282010,0.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,saint556,282010,13.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4267750,76561198273508956,80,0.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267751,76561198282090798,80,0.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267752,943525,80,0.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267753,76561198283312749,80,9.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267754,76561198312638244,80,99.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

se borra las filas que tienen valores 0 en las columnas playtime_forever y playtime_2weeks, ya que no se las usara para los puntos 3 y 4 de la funcion

In [254]:
df_genre = df_genre.loc[~((df_genre['playtime_forever'] == 0) )]
df_genre

,user_id,item_id,playtime_forever,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
27,UTNerd24,282010,5.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
31,saint556,282010,13.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
32,chidvd,282010,110.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
33,aerpub,282010,13.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
34,lucifer666678,282010,8.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4267744,76561198208507532,80,203.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267746,76561198221578852,80,244.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267747,EnVyIsSmexy,80,7.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267753,76561198283312749,80,9.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4267754,76561198312638244,80,99.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [253]:
df_genre[df_genre['user_id'] == 'UTNerd24']

,user_id,item_id,playtime_forever,Accounting,Action,Adventure,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,...,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
27,UTNerd24,282010,5.0,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
216,UTNerd24,70,16.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8239,UTNerd24,2400,1.0,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
17098,UTNerd24,2420,5.0,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
23405,UTNerd24,4000,101311.0,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4224512,UTNerd24,50,519.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4234006,UTNerd24,10,5.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4247201,UTNerd24,130,355.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4257745,UTNerd24,13230,18760.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4259041,UTNerd24,80,46.0,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
def genre(genero:str):
    # usamos una maskara para filtrar las columnas con que vamos a trabajar
    ranking = data_items[data_items['genres_games'] == genero][['user_id', 'user_url', 'playtime_forever']]

    # Realizar la operación de agrupación y suma
    ranking = ranking.groupby('user_id').agg({'playtime_forever': 'sum', 'user_url': 'first'})

    # Ordenar el ranking por 'playtime_forever'
    ranking = ranking.sort_values(by='playtime_forever', ascending=False).reset_index()

    # ordenamos las columnas
    ranking=ranking[['user_id','user_url','playtime_forever']]

    # Mostrar las 5 mejores filas
    ranking.head(5)
    
    return(ranking.head(5))